# Uncomment the next line to define a global platform for your project

platform :ios, '12.0'

source "https://gitlab.com/qLiardeaux/Specs.git"

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'QLCalendar'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
